services:
  - type: web
    name: sat-math-app
    env: node
    buildCommand: npm install && NODE_OPTIONS='--openssl-legacy-provider' npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
    buildFilter:
      paths:
      - package.json
      - SAT2/package.json
      - server.js
      - config/**
      - SAT2/**
